//
//  FeatureToggles.generated.swift
//  FeatureToggles
//
//  Generated by codegen.
//

import Foundation

public extension FeatureTogglesProvider {
    /// Defines the main screen background color
    var backgroundColor: String { value(String.self, for: "backgroundColor", fallback: "red") }
    /// Text to present as subtitle
    var subtitleText: String { value(String.self, for: "subtitleText", fallback: "there!") }
    /// If the subtitle has to be presented or not.
    var subtitleVisible: Bool { value(Bool.self, for: "subtitleVisible", fallback: true) }
    /// This is the color used by the main text
    var textColor: String { value(String.self, for: "textColor", fallback: "white") }
    /// Text presented as main title
    var title: String { value(String.self, for: "title", fallback: "Hello") }
    /// Defines a vertical offset for the main content.
    var verticalOffset: NSNumber { value(NSNumber.self, for: "verticalOffset", fallback: 0) }
}
